# Generated by Django 5.1.2 on 2024-10-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthday_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
