# Generated by Django 5.1.2 on 2024-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_address1_user_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
