# Generated by Django 5.1.2 on 2024-10-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
