# Generated by Django 5.1.2 on 2024-10-31 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna',
            options={},
        ),
        migrations.RemoveField(
            model_name='qna',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='top_fixed',
        ),
        migrations.AddField(
            model_name='qna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성 시각'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시각'),
        ),
        migrations.AlterModelTable(
            name='qna',
            table=None,
        ),
    ]
