# Generated by Django 5.1.2 on 2024-10-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_alter_qna_options_remove_qna_hits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qnaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'qnacategories',
            },
        ),
    ]
