# Generated by Django 5.1.2 on 2024-10-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_qnacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qna.qnacategory'),
        ),
    ]
