# Generated by Django 5.1.2 on 2024-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_qna_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
