# Generated by Django 5.1.2 on 2024-11-04 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_qna_answer_qna_answered_at_qna_answered_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='answered_by',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='qna.qna')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
