# Generated by Django 5.1.2 on 2024-11-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_remove_qna_answer_remove_qna_answered_at_and_more'),
        ('shop', '0006_qnacategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnacategory',
            old_name='slug',
            new_name='qna_slug',
        ),
        migrations.RemoveField(
            model_name='qnacategory',
            name='name',
        ),
        migrations.AddField(
            model_name='qna',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qnas', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qnacategory',
            name='qna_name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
