# Generated by Django 5.2.5 on 2025-08-17 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_category_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='selected_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.colorcategory', verbose_name='선택한 색상'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.sizecategory', verbose_name='선택한 사이즈'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedproduct',
            unique_together={('order', 'product')},
        ),
    ]
