# Generated by Django 4.0.3 on 2024-10-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_id_product_p_stock_alter_product_p_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_stock',
            new_name='stock',
        ),
    ]
