# Generated by Django 5.1.2 on 2024-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_nestedsubcategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_name', models.CharField(max_length=50, unique=True)),
                ('qna_slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'qnacategories',
            },
        ),
    ]
