# Generated by Django 5.1.2 on 2024-11-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_qnacategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QnaCategory',
        ),
    ]
