# Generated by Django 5.1.3 on 2024-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='imp_uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
