# Generated by Django 5.1.3 on 2024-12-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='imp_uid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
