# Generated by Django 5.1.3 on 2024-12-18 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_payment_imp_uid_alter_payment_merchant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='merchant_uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
    ]
