# Generated by Django 5.1.3 on 2024-12-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
