# Generated by Django 4.1.7 on 2025-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_cartproduct_order_orderedproduct_orderpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', '주문요청'), ('failed_payment', '결제실패'), ('paid', '결제완료'), ('prepared_product', '상품준비중'), ('shipped', '배송중'), ('delivered', '배송완료'), ('cancelled', '주문취소'), ('confirmed', '구매확정')], db_index=True, default='requested', max_length=20, verbose_name='진행상태'),
        ),
    ]
