# Generated by Django 5.1.2 on 2024-12-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user_cartitem_color_cartitem_size'),
        ('shop', '0010_alter_like_user_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Color',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.sizecategory'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.colorcategory'),
        ),
    ]
